spring.application.name=resource-allocator-backend
server.port=8080

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:resourceallocator;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Consola H2: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Fechas como ISO (yyyy-MM-dd)
spring.jackson.serialization.write-dates-as-timestamps=false